### ISSUE TITLE
Double Page Layout?

### ISSUE THREAD

**Issue by tf** [joseph/Monocle#12]
Hi,

we would like to display two pages in landscape mode. Do you think this might be possible with Monocle? I am currently in the process of getting to know the source code to find out whether CSS columns might be used to this end.

Do you see any conceptual obstacles?

Regards,
Tim

**Comment by ssomnoremac** [comment]
Try using the [double_pages.js] (https://github.com/TEA-ebook/teabook-open-reader/blob/master/app/assets/javascripts/monocle/flippers/double_pages.js.coffee) from the TEA-ebook project. Even though they don't give credit, it's basically the same as Monocle.js, using the same flippers, except you'll have to change the references from 'App' to 'Monocle' after you convert the whole file to normal javascript and add it to monoctrl.js at the end. 

You'll have to also change the width of .monelem_page to 50%  and monelem_page.right  left: 50%;
