### ISSUE TITLE
[Android 5.x] Content isn't shown

### ISSUE THREAD

**Issue by osanwe** [joseph/Monocle#260]
There is a problem with Android Lollipop. WebView doesn't show book content. On Android 4.x and bellow all work correctly.

More info I've posted on StackOverflow: http://stackoverflow.com/questions/31750611/android-lollipop-webview-does-not-show-iframe-content

**Comment by AbhilashThomas** [comment]
You can try uninstalling the webview system update.

**Comment by joseph** [comment]
Try the latest `master`. I expect this is fixed by https://github.com/joseph/Monocle/issues/259.
