### ISSUE TITLE
hyperlinks, magnifier

### ISSUE THREAD

**Issue by fruscica** [joseph/Monocle#71]
hello all,

_great_ app.  am in the process of formatting an ebook using monocle.  not always easy to identify the code needed to produce certain effects.  in particular, i can't replicate the hyperlinks that are seen in the panels test.  nor have i been able to add the magnifier control to the below script:

```
  // Initialize the reader element.
  Monocle.Events.listen(
    window,
    'load',
    function () { window.reader = Monocle.Reader('reader', null, {flipper: Monocle.Flippers.Instant, panel:Monocle.Panels.Marginal}, function (reader) {
      reader.moveTo({ page: 1 });
    }); }
  );
```

thx kindly for any insight.

best,

frank

**Comment by fedorinoGore** [comment]
Years are passing by ^) But I have the same issue with scrubber. Could you please share - what do you mean by "it turns out that i have to link to the css for the controls."?
